Models/Model/Bank.cs
using System;
using System.Collections.Generic;

namespace GeneralSalesDb.Models.Model
{
    public partial class Bank
    {
        public Bank()
        {
            BankDeal = new HashSet<BankDeal>();
        }

        public int BankId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public int? DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<BankDeal> BankDeal { get; set; }
    }
}

Models/Model/Customer.cs
using System;
using System.Collections.Generic;

namespace GeneralSalesDb.Models.Model
{
    public partial class Customer
    {
        public Customer()
        {
            CustomerDeal = new HashSet<CustomerDeal>();
            PrintTable = new HashSet<PrintTable>();
            Sale = new HashSet<Sale>();
        }

        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public int? DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<CustomerDeal> CustomerDeal { get; set; }
        public virtual ICollection<PrintTable> PrintTable { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
    }
}

Models/Model/Dealer.cs
using System;
using System.Collections.Generic;

namespace GeneralSalesDb.Models.Model
{
    public partial class Dealer
    {
        public Dealer()
        {
            Purchase = new HashSet<Purchase>();
        }

        public int DealerId { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public int? DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}

Models/ViewModels/BankViewModels/BankViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GeneralSalesDb.Models.ViewModels
{
    public class BankViewModel
    {

        public int BankId { get; set; }

        [Display(Name = "بانک / صراف:")]
        [Required(ErrorMessage = "بانک / صراف نوم ولیکئ!!")]
        public string NameB { get; set; }

        [Display(Name = "موبایل:")]
        [Required(ErrorMessage = "مبائیل شمېره داخل کړئ!!")]
        public string PhoneB { get; set; }

        [Display(Name = "آدرس:")]
        [Required(ErrorMessage = " آدرس ولیکئ !!")]
        public string AddressB { get; set; }
    }
}

Models/ViewModels/DealViewModels/DealViewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GeneralSalesDb.Models.ViewModels
{
    public class DealViewModel
    {


        [Required(ErrorMessage = "بیل / رسید نمبر ولیکئ")]
        public string BillNo { get; set; }

        [Required(ErrorMessage = "کهاتدار انتخاب کړئ")]
        public int DealerId { get; set; }

        [Required(ErrorMessage = "مشترې انتخاب کړئ")]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "پولې واحد انتخاب کړئ")]
        public int CurrencyId { get; set; }

        [Required(ErrorMessage = "سیف پولې واحد انتخاب کړئ")]
        public int Currency2Id { get; set; }

        [Required(ErrorMessage = "جمع / بنام انتخاب کړئ")]
        public string Type { get; set; }

        [Required(ErrorMessage = "پیسو اندازه")]
        public double Amount { get; set; }

        [Required(ErrorMessage = "پیسو اندازه")]
        public double Amount2 { get; set; }

        public string Detail { get; set; }


    }
}

Models/ViewModels/DealerViewModels/CustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GeneralSalesDb.Models.ViewModels
{
    public class CustomerViewModel
    {
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "مشترې نوم ولیکئ")]
        public string CusName { get; set; }


        [Required(ErrorMessage = "مشترې د پلار نوم ولیکئ")]
        public string CusFName { get; set; }


        [Required(ErrorMessage = "مشترې آدرس ولیکئ")]
        public string CusAddress { get; set; }

        [Required(ErrorMessage = "مشترې موبایل نمبر ولیکئ")]
        public string CusPhone { get; set; }

    }
}

Models/ViewModels/DealerViewModels/DealerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GeneralSalesDb.Models.ViewModels
{
    public class DealerViewModel
    {
        public int DealerId { get; set; }

        [Required(ErrorMessage = "کهاتدار نوم ولیکئ")]
        public string Name { get; set; }


        [Required(ErrorMessage = "کهاتدار دپلار نوم ولیکئ")]
        public string FName { get; set; }


        [Required(ErrorMessage = "کهاتدار آدرس ولیکئ")]
        public string Address { get; set; }

        [Required(ErrorMessage = "کهاتدار موبایل نمبر ولیکئ")]
        public string Phone { get; set; }

    }
}

Controllers/DealController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using GeneralSalesDb.Models;
using GeneralSalesDb.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeneralSalesDb.Models.Model;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.EntityFrameworkCore;

namespace GeneralSalesDb.Controllers
{
    [Authorize(Roles = "Finance Department,Admin Department,Super Admin")]
    public class DealController : Controller
    {
        GeneralSalesDbContext db = new GeneralSalesDbContext();
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment hostingEnvironment;

        int depId = 0;
        public DealController(UserManager<ApplicationUser> userManager, IWebHostEnvironment hostingEnvironment)
        {
            this.userManager = userManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            depId = userManager.GetUserAsync(User).Result.DepartmentId;

            var dealers = (from d in db.Dealer
                           where d.DepartmentId == depId && d.Status == "Unlocked"
                           select new SelectListItem()
                           {
                               Text = d.Name + " / " + d.Fname,
                               Value = d.DealerId.ToString()
                           }).ToList();
            ViewBag.dealers = dealers;

            var customers = (from d in db.Customer
                             where d.DepartmentId == depId && d.Status == "Unlocked"
                             select new SelectListItem()
                             {
                                 Text = d.Name + " / " + d.Fname,
                                 Value = d.CustomerId.ToString()
                             }).ToList();
            ViewBag.customers = customers;


            var expenseType = (from d in db.ExpenceType
                               where d.DepartmentId == depId
                               select new SelectListItem()
                               {
                                   Text = d.ExpenceType1,
                                   Value = d.ExpenceTypeId.ToString()
                               }).ToList();
            ViewBag.expenseType = expenseType;

            var bank = (from d in db.Bank
                        where d.DepartmentId == depId
                        select new SelectListItem()
                        {
                            Text = d.Name,
                            Value = d.BankId.ToString()
                        }).ToList();
            ViewBag.bank = bank;

            return View();
        }

        public async Task<JsonResult> FetchSerialNumber()
        {
            depId = userManager.GetUserAsync(User).Result.DepartmentId;

            long serialNumber = db.SerialTable.Where(x => x.DepartmentId == depId && x.SerialNumberId == 1).Select(x => x.CashSerial).FirstOrDefault();

            if (serialNumber == 0)
            {
                SerialTable serial = new SerialTable
                {
                    SaleSerial = 1,
                    DepartmentId = depId,
                };

                db.SerialTable.Add(serial);
                await db.SaveChangesAsync();

                return Json(new
                {
                    serialNumber = 1,
                });
            }

            return Json(new
            {
                serialNumber = serialNumber,
            });
        }

        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRecord(long dealId, string record,int dealerId,int currencyId)
        {
            depId = userManager.GetUserAsync(User).Result.DepartmentId;

            if (record == "1")
            {
                var deals = await db.DealerDeal.Where(x => x.DealId >= dealId && x.DealerId==dealerId && x.CurrencyId == currencyId).ToListAsync();

                var deal = await db.DealerDeal.Where(x => x.DealId == dealId && x.DealerId == dealerId && x.CurrencyId == currencyId).FirstOrDefaultAsync();

                var debit = deal.Debit;
                var credit = deal.Credit;

                foreach (var item in deals)
                {
                    item.Balance += debit;
                    item.Balance -= credit;

                    db.DealerDeal.Update(item);
                }

                if (deals.Count == 1)
                {
                    var serial = db.SerialTable.Where(x => x.DepartmentId == depId && x.SerialNumberId == 1).FirstOrDefault();

                    serial.CashSerial -= 1;

                    db.SerialTable.Update(serial);
                }

                var cash = await db.CashInHand.Where(x => x.DealId == dealId && x.CurrencyId == currencyId).FirstOrDefaultAsync();

                if (cash != null)
                {
                    db.CashInHand.Remove(cash);
                }

                db.DealerDeal.Remove(deal);

                await db.SaveChangesAsync();

                return Json("کهاتدار ریکارډ حذف شو");
            }
            else
            {
                var deals = await db.CustomerDeal.Where(x => x.DealId >= dealId && x.CustomerId == dealerId && x.CurrencyId == currencyId).ToListAsync();

                var deal = await db.CustomerDeal.Where(x => x.DealId == dealId && x.CustomerId == dealerId && x.CurrencyId == currencyId).FirstOrDefaultAsync();

                var debit = deal.Debit;
                var credit = deal.Credit;

                foreach (var item in deals)
                {
                    item.Balance -= debit;
                    item.Balance += credit;

                    db.CustomerDeal.Update(item);
                }

                if (deals.Count == 1)
                {
                    var serial = db.SerialTable.Where(x => x.DepartmentId == depId && x.SerialNumberId == 1).FirstOrDefault();

                    serial.CashSerial -= 1;

                    db.SerialTable.Update(serial);
                }


                var cash = await db.CashInHand.Where(x => x.CusDealId == dealId  && x.CurrencyId == currencyId).FirstOrDefaultAsync();

                if (cash != null)
                {
                    db.CashInHand.Remove(cash);
                }

                db.CustomerDeal.Remove(deal);


                await db.SaveChangesAsync();

                return Json("مشترې ریکارډ حذف شو");
            }
        }

        [Authorize(Policy = "InsertRolePolicy")]
        public async Task<IActionResult> AddDealInfo(DealViewModel model, [FromForm] IFormFile image)
        {

            if (ModelState.IsValid)
            {
                try
                {

                    var email = userManager.GetUserAsync(User).Result.Email;

                    depId = userManager.GetUserAsync(User).Result.DepartmentId;


                    double cr = 0.0;
                    double cr2 = 0.0;
                    double deb = 0.0;
                    double deb2 = 0.0;

                    var balance = 0.0;

                    var serial = db.SerialTable.Where(x => x.DepartmentId == depId && x.SerialNumberId==1).FirstOrDefault();

                    var sno = serial.CashSerial;

                    serial.CashSerial += 1;

                    db.SerialTable.Update(serial);

                    if (model.CustomerId != 0)
                    {

                        if (model.Type == "Debit")
                        {
                            deb = model.Amount;
                            deb2 = model.Amount2;

                            balance = model.Amount;
                        }
                        else
                        {
                            cr = model.Amount;
                            cr2 = model.Amount2;

                            balance = -model.Amount;
                        }

                        var dealing = await db.CustomerDeal.Where(x =>
                        x.CustomerId == model.CustomerId
                        && x.CurrencyId == model.CurrencyId
                        && x.DepartmentId == depId).OrderByDescending(x => x.DealId).FirstOrDefaultAsync();



                        if (dealing != null)
                        {
                            balance += dealing.Balance;
                        }

                        CustomerDeal deal = new CustomerDeal
                        {
                            BillNo = model.BillNo,
                            Debit = deb,
                            Credit = cr,
                            Balance = balance,
                            CustomerId = model.CustomerId,
                            Date = DateTime.Now.Date,
                            CurrencyId = model.CurrencyId,
                            Employee = email,
                            Type = model.Type,
                            Detail = model.Detail,
                            SerialNumber = sno,
                            DepartmentId = depId,

                        };

                        await db.CustomerDeal.AddAsync(deal);
                        await db.SaveChangesAsync();

                        CashInHand cash = new CashInHand
                        {
                            Debit = deb2,
                            Credit = cr2,
                            Date = DateTime.Now.Date,
                            CurrencyId = model.Currency2Id,
                            CusDealId = deal.DealId,
                            Description = model.Detail,
                            DepartmentId = depId
                        };

                        await db.CashInHand.AddAsync(cash);

Views/Deal/Customers.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>$("#customerActive").addClass("active")</script>


<div class="card" id="purchaseList">
    <div class="card-header ">
        <h2 class="text-center  alert bg-primary box-shadow-1">د مشتریانو د کهاتو تفصیل</h2>
    </div>
    <div id="divCustomers">
        <table class="table table-responsive-md table-bordered dataex-fixh-basic dataTable" id="tblList">
            <thead>
                <tr role="row">
                    <th>مشترې نوم</th>
                    <th>د پلار نوم</th>
                    <th>موبایل</th>
                    <th>آدرس </th>
                    <th>انتخاب کړئ</th>
                </tr>
            </thead>
            <tbody></tbody>

        </table>
    </div>

    <div id="divCustomerDeal" class="col-md-12" style="display:none">
        <form data-ajax="true" asp-action="FetchDealInfoByDate" asp-controller="Deal" data-ajax-success="DataFetchedByDate(data)" data-ajax-method="post" id="frmDealerDeal">
            <div class="row" style="align-items: center; justify-content: center;">

                <input type="hidden" name="customerId" id="customerId" />

                <div class="col-md-3 mx-0 px-0" style="display: flex; align-items: center;margin-bottom:10px">
                    <label class="col-md-4"> پولې واحد:</label>
                    <select onchange="FetchDealerDeal()" name="currencyId" id="currencyId" class="form-control">
                        <option selected value="1">افعانۍ</option>
                        <option value="2">کلدارې</option>
                        <option value="3">ډالر</option>
                    </select>
                </div>

                <div class="col-md-3  m-0 p-0" style="display: flex; align-items: center;">
                    <label class="col-md-4">د نیټې څخه</label>
                    <input class="form-control" required name="fromDate" id="fromDate" type="date" style="height:45px;">
                </div>
                <div class="col-md-3  m-0 p-0" style="display: flex; align-items: center;">
                    <label class="col-md-4">تر نیټې پورې</label>
                    <input class="form-control" required name="toDate" id="toDate" type="date" style="height:45px;">
                </div>
                &nbsp; &nbsp;
                <div class="col-md-1  m-0 p-0" style="display: flex; align-items: center;">
                    <button type="submit" class="btn btn-default  btn-info"> ښودل</button>
                    &nbsp;
                    <button type="button" id="btnLoadCurrentMonth" onclick="resetForm()" class="btn btn-default  btn-warning">پاکول</button>

                </div>
                <button type="button" id="btnBack" onclick="backToList()" class="btn btn-success mx-1 btn-icon-sm">مشتریانو لیست <i class="fa fa-list"></i></button>
            </div>
        </form>
        <table class="table table-striped  table-condensed table-bordered " id="CustomerTable">
            <thead class="scrollable-container ps--scrolling-x ">
                <tr role="row">
                    <th class="col-md-2">#</th>
                    <th class="col-md-2">بیل / رسید نمبر</th>
                    <th class="col-md-2">نیټه</th>
                    <th class="col-md-2">تفصیل</th>
                    <th class="col-md-2">مشترې</th>
                    <th class="col-md-2">پلار نوم</th>
                    <th class="col-md-1">موبایل</th>
                    <th class="col-md-2">کارمند</th>
                    <th class="col-md-2">پولې واحد</th>
                    <th class="col-md-1">بنام</th>
                    <th class="col-md-1">جمع</th>
                    <th class="col-md-1">باقې</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

</div>

<!--Image modal -->
<div class="modal fade text-left" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel35"
     aria-hidden="true">

    <div class="modal-dialog modal-lg p-4" role="document">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="position: absolute; padding: 10px;  ">
            <span aria-hidden="true" style="color: #f9f9f9; font-size: larger; cursor: pointer ">&times;</span>
        </button>
        <img src="" class="round" style="height:100%;width:100%;" id="imageZoom" />
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script>

        $(document).ready(function () {
            FetchCustomers();
        })

        function FetchCustomers() {

            $.ajax({
                url: '/Deal/FetchCustomers/',
                type: 'POST',
                contentType: "application/json",
                data: '{}',
                datatype: "JSON",
                success: function (result) {

                    var tr = "";
                    $.each(result, function (i, col) {
                        tr += "  <tr> ";
                        tr += "      <td>" + col.name + "</td> ";
                        tr += "      <td>" + col.fname + "</td> ";
                        tr += "      <td>" + col.phone + "</td> ";
                        tr += "      <td>" + col.address + "</td> ";
                        tr += '      <td><button type="submit" class="btn btn-primary" onclick="FetchCustomerDeal(' + col.customerid + ')" ><i" class="ft-info" ></i></button></td>';
                        tr += "  </tr>";
                    });
                    $("#tblList>tbody").html("").html(tr);

                    $("#tblList").DataTable({
                        stateSave: true,
                        "lengthMenu": [[5, 10, 20, -1], [5, 15, 50, "ټول"]],
                        "pageLength": 5,
                        "language": {
                            "emptyTable": "په جدول کې معلومات شتون نه لري",
                            "info": "د <b>( _START_  )</b> تر <b>( _END_  )</b> د <b>( _TOTAL_ )</b> ریکاروډونو څخه.",
                            "infoFiltered": "( <b>( _MAX_ )</b> ریکارډونه شتون لرې )",
                            "infoPostFix": "",

                            "lengthMenu": "ښودل_MENU_ ریکارډونو",
                            "search": "پلټنه<span id='tblSearch' class='fa fa-search'></span> ",
                            "searchPlaceholder": "پلټنه",
                            "zeroRecords": "پدی نوم هیڅ ریکارډ پیدا نشو ",
                            "paginate": {
                                "first": "لومړۍ پاڼه",
                                "previous": "مخکې",
                                "next": "وروسته",
                                "last": "پای"
                            },
                        },
                    });
                }
            })

        }

        function DataFetchedByDate(data) {
            PassDataToTable(data);
        }

        function FetchCustomerDeal(customerId) {
            $("#customerId").val(customerId)
            FetchDealerDeal()
        }

        function FetchDealerDeal() {

            $("#divCustomers").hide(600);


            if ($("#fromDate").val() == "" && $("#toDate").val() == "") {

                $.ajax({
                    url: '/Deal/FetchCustomerDealInfo/?customerId=' + $("#customerId").val() + '&currencyId=' + $("#currencyId :selected").val() + '',
                    type: 'POST',
                    contentType: "application/json",
                    datatype: "JSON",
                    success: function (result) {

                        PassDataToTable(result);
                    }
                })
            }

        }

        function PassDataToTable(data) {

            var Cus = "";

            $("#divCustomerDeal").show(400);

            $.each(data, function (i, col) {

                Cus += " <tr >";
                Cus += "      <td> " + (i + 1) + " </td>";
                Cus += "     <td>  " + col.billNo + " </td>";
                Cus += "     <td>  " + col.date + " </td>";
                Cus += "      <td> " + col.details + "  </td>";
                Cus += "      <td> " + col.name + " </td>";
                Cus += "      <td> " + col.fname + " </td>";
                Cus += "      <td> " + col.phone + " </td>";
                Cus += "      <td> " + col.employee + "  </td>";
                Cus += "      <td> " + col.currency + "  </td>";
                Cus += "      <td dir='ltr'> " + parseFloat(col.debit).toFixed(3) + " </td>";
                Cus += "      <td dir='ltr'> " + parseFloat(col.credit).toFixed(3) + " </td>";
                Cus += "      <td dir='ltr'> " + parseFloat(col.balance).toFixed(3) + " </td>";
                Cus += "      </tr>";
            });

            var table = $("#CustomerTable").dataTable();
            table.fnDestroy();

            $("#CustomerTable>tbody").html("").html(Cus);
            $("#CustomerTable").DataTable({
                stateSave: true,
                dom: 'Blfrtip',

                buttons: [
                    'colvis',
                    {
                        extend: 'print',
                        //customize: function (win) {
                        //    $(win.document.body).attr('padding', '30px');
                        //},
                        footer: true,
                        exportOptions: {
                            columns: ':visible'
                        }

                    },
                    {
                        extend: 'excel', footer: true, exportOptions: {
                            columns: ':visible'
                        },
                    },
                    {
                        extend: 'copy', footer: true, exportOptions: {
                            columns: ':visible'
                        },
                    }
                ],

                responsive: true,

                colReorder: true,
                "lengthMenu": [[5, 10, 20, -1], [5, 15, 50, "ټول"]],
                "pageLength": 5,
                "language": {
                    "emptyTable": "په جدول کې معلومات شتون نه لري",
                    "info": "د <b>( _START_  )</b> تر <b>( _END_  )</b> د <b>( _TOTAL_ )</b> ریکاروډونو څخه.",
                    "infoFiltered": "( <b>( _MAX_ )</b> ریکارډونه شتون لرې )",
                    "infoPostFix": "",

                    "lengthMenu": "ښودل_MENU_ ریکارډونو",
                    "search": "پلټنه<span id='tblSearch' class='fa fa-search'></span> ",
                    "searchPlaceholder": "پلټنه",
                    "zeroRecords": "پدی نوم هیڅ ریکارډ پیدا نشو ",
                    "paginate": {
                        "first": "لومړۍ پاڼه",
                        "previous": "مخکې",
                        "next": "وروسته",
                        "last": "پای"
                    },
                },

            });

            $(".buttons-print").text("").html("<i class='ft-printer'></i>");
            $(".buttons-copy").text("").html("<i class='ft-copy'></i>");
            $(".buttons-excel").text("").html("<i class='fa fa-file-excel-o'></i>");
            $(".buttons-colvis").text("").html("<i class='ft-eye-off'></i>");
            $('.buttons-copy, .buttons-print, .buttons-excel,.buttons-colvis').addClass('btn btn-primary ');

        }

        function backToList() {
            $("#divCustomers").show(400);
            $("#divCustomerDeal").hide(650);
        }

        function resetForm() {

            $("#fromDate").val("");

            $("#toDate").val("");

            FetchDealerDeal()
        }

        function fnZoomImageCustomer(path) {

            $("#imageZoom").attr("src", path);
            $("#imageModal").modal("show")
        }
    </script>

}

Views/Deal/Index.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>$("#roznamchaActive").addClass("active")</script>

<div class="card">
    <div class="col-md-12 px-2 pt-1">
        <h2 class="text-center alert bg-yellow bg-darken-2 box-shadow-1" style="background-color:#ffffff;">روزنامچه </h2>
    </div>
    <div class="card-content">
        <div class="card-body">
            <ul class="nav nav-tabs nav-top-border no-hover-bg">
                <li class="nav-item">
                    <a class="nav-link active" id="baseIcon-tab11" data-toggle="tab" aria-controls="tabIcon11" href="#tabIcon11" aria-expanded="true"><i class="fa fa-user-o"></i> کهاته </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " id="baseIcon-tab12" data-toggle="tab" aria-controls="tabIcon12" href="#tabIcon12" aria-expanded="false"><i class="fa fa-university"></i> بانک / صراف</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " id="baseIcon-tab133" data-toggle="tab" aria-controls="tabIcon13" href="#tabIcon13" aria-expanded="false"><i class="fa fa-money"></i> مصارف</a>
                </li>
            </ul>
            <div class="tab-content pt-1">

                <div role="tabpanel" class="tab-pane active" id="tabIcon11" aria-expanded="true" aria-labelledby="baseIcon-tab11">
                    @await Html.PartialAsync("~/views/Deal/_DealViewPartial.cshtml")
                </div>

                <div class="tab-pane " id="tabIcon12" aria-labelledby="baseIcon-tab12">
                    @await Html.PartialAsync("~/views/Deal/_BankViewPartial.cshtml")
                </div>

                <div class="tab-pane " id="tabIcon13" aria-labelledby="baseIcon-tab13">
                    @await Html.PartialAsync("~/views/Deal/_ExpenseViewPartial.cshtml")
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}