Models/Model/Dealer.cs
using System;
using System.Collections.Generic;

namespace GeneralSalesDb.Models.Model
{
    public partial class Dealer
    {
        public Dealer()
        {
            Purchase = new HashSet<Purchase>();
        }

        public int DealerId { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public int? DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}

Models/ViewModels/DealerViewModels/DealerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GeneralSalesDb.Models.ViewModels
{
    public class DealerViewModel
    {
        public int DealerId { get; set; }

        [Required(ErrorMessage = "کهاتدار نوم ولیکئ")]
        public string Name { get; set; }


        [Required(ErrorMessage = "کهاتدار دپلار نوم ولیکئ")]
        public string FName { get; set; }


        [Required(ErrorMessage = "کهاتدار آدرس ولیکئ")]
        public string Address { get; set; }

        [Required(ErrorMessage = "کهاتدار موبایل نمبر ولیکئ")]
        public string Phone { get; set; }

    }
}

Controllers/DealerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using GeneralSalesDb.Models;
using GeneralSalesDb.Models.Model;
using GeneralSalesDb.Models.ViewModels;

namespace GeneralSalesDb.Controllers
{
    [Authorize(Roles = "Finance Department,Admin Department,Purchase Department,Stock Department")]
    public class DealerController : Controller
    {
        GeneralSalesDbContext db = new GeneralSalesDbContext();
        private readonly UserManager<ApplicationUser> userManager;
        int depId = 0;
        public DealerController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        /// Dealers ///
        [Authorize(Policy = "InsertRolePolicy")]
        public async Task<IActionResult> DealerRegistration(DealerViewModel model)
        {
            if (ModelState.IsValid)
            {
                depId = userManager.GetUserAsync(User).Result.DepartmentId;

                if (model.DealerId != 0)
                {
                    var rec = await db.Dealer.FindAsync(model.DealerId);
                    if (rec == null)
                    {
                        return View("Error");
                    }
                    rec.DealerId = model.DealerId;
                    rec.Name = model.Name;
                    rec.Fname = model.FName;
                    rec.Address = model.Address;
                    rec.Phone = model.Phone.ToString();

                    db.Dealer.Update(rec);
                    await db.SaveChangesAsync();

                    return Json("کهاتدار معلومات تغیر شو");
                }
                else
                {
                    try
                    {
                        Dealer dealer = new Dealer()
                        {
                            Name = model.Name,
                            Fname = model.FName,
                            Address = model.Address,
                            Phone = model.Phone.ToString(),
                            Status = "Unlocked",
                            DepartmentId = depId,
                        };
                        db.Dealer.Add(dealer);
                        await db.SaveChangesAsync();
                    }
                    catch (Exception e)
                    {
                        throw new Exception(e.Message);
                    }
                    return Json("کهاتدار معلومات ذخیره شو");
                }
            }
            return View("Error");
        }

        public JsonResult FetchDealers()
        {
            depId = userManager.GetUserAsync(User).Result.DepartmentId;

            var dealer = (from d in db.Dealer
                          where d.DepartmentId == depId
                                       select new
                                       {
                                           dealerId = d.DealerId,
                                           name = d.Name,
                                           fName = d.Fname,
                                           address = d.Address,
                                           phone = d.Phone,
                                           status = d.Status,
                                       }).ToList().OrderByDescending(r => r.dealerId);
            return Json(dealer);
        }

        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteDealer(DealerViewModel model)
        {
            if (model.DealerId != 0)
            {
                var dealer = await db.Dealer.FindAsync(model.DealerId);
                if (dealer == null)
                {
                    return View("Error");
                }

                try
                {
                    db.Dealer.Remove(dealer);
                    await db.SaveChangesAsync();
                    return Json("ریکارډ حذف شو");
                }
                catch (Exception)
                {
                    return Json("تاسو نه شی کولی نوموړی ریکارد حذف کړی");
                }
            }
            return NotFound();
        }

        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> LockDealerAccount(int dealerId, string trueFalse)
        {
            var user = await db.Dealer.FindAsync(dealerId);

            if (trueFalse == "lock")
            {
                user.Status = "Locked";

                db.Dealer.Update(user);

                await db.SaveChangesAsync();

                return Json("true");
            }
            else
            {

                user.Status = "Unlocked";

                db.Dealer.Update(user);

                await db.SaveChangesAsync();

                return Json("true");
            }


        }

        /// Customers ///
       [Authorize(Policy = "InsertRolePolicy")]
        public async Task<IActionResult> CustomerRegistration(CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                depId = userManager.GetUserAsync(User).Result.DepartmentId;

                if (model.CustomerId != 0)
                {
                    var rec = await db.Customer.FindAsync(model.CustomerId);
                    if (rec == null)
                    {
                        return View("Error");
                    }
                    rec.CustomerId = model.CustomerId;
                    rec.Name = model.CusName;
                    rec.Fname = model.CusFName;
                    rec.Address = model.CusAddress;
                    rec.Phone = model.CusPhone.ToString();

                    db.Customer.Update(rec);
                    await db.SaveChangesAsync();

                    return Json("مشترې معلومات تغیر شو");
                }
                else
                {
                    try
                    {
                        Customer Customer = new Customer()
                        {
                            Name = model.CusName,
                            Fname = model.CusFName,
                            Address = model.CusAddress,
                            Phone = model.CusPhone.ToString(),
                            Status = "Unlocked",
                            DepartmentId = depId,
                        };
                        db.Customer.Add(Customer);
                        await db.SaveChangesAsync();
                    }
                    catch (Exception e)
                    {
                        throw new Exception(e.Message);
                    }
                    return Json("مشترې معلومات ذخیره شو");
                }
            }
            return View("Error");
        }

        public JsonResult FetchCustomers()
        {
            depId = userManager.GetUserAsync(User).Result.DepartmentId;

            var Customer = (from d in db.Customer
                            where d.DepartmentId==depId
                          select new
                          {
                              customerId = d.CustomerId,
                              name = d.Name,
                              fName = d.Fname,
                              address = d.Address,
                              phone = d.Phone,
                              status = d.Status,
                          }).ToList().OrderByDescending(r => r.customerId);
            return Json(Customer);
        }

        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteCustomer(CustomerViewModel model)
        {
            if (model.CustomerId != 0)
            {
                var Customer = await db.Customer.FindAsync(model.CustomerId);
                if (Customer == null)
                {
                    return View("Error");
                }

                try
                {
                    db.Customer.Remove(Customer);
                    await db.SaveChangesAsync();
                    return Json("ریکارډ حذف شو");
                }
                catch (Exception)
                {
                    return Json("تاسو نه شی کولی نوموړی ریکارد حذف کړی");
                }
            }
            return NotFound();
        }

        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> LockAccount(int dealerId,string trueFalse)
        {
            var user = await db.Customer.FindAsync(dealerId);

            if (trueFalse == "lock")
            {
                user.Status = "Locked";

                db.Customer.Update(user);

                await db.SaveChangesAsync();

                return Json("true");
            }
            else
            {

                user.Status = "Unlocked";

                db.Customer.Update(user);

                await db.SaveChangesAsync();

                return Json("true");
            }


        }


        /// Banks ///
        [Authorize(Policy = "InsertRolePolicy")]
        public async Task<IActionResult> BankRegistration(BankViewModel model)
        {
            if (ModelState.IsValid)
            {
                depId = userManager.GetUserAsync(User).Result.DepartmentId;

                if (model.BankId != 0)
                {
                    var rec = await db.Bank.FindAsync(model.BankId);
                    if (rec == null)
                    {
                        return View("Error");
                    }
                    rec.BankId = model.BankId;
                    rec.Name = model.NameB;
                    rec.Address = model.AddressB;
                    rec.Phone = model.PhoneB.ToString();

                    db.Bank.Update(rec);
                    await db.SaveChangesAsync();

                    return Json($"{model.NameB} معلومات تغیر شو");
                }
                else

Views/Dealer/Index.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>$("#dealerRegisterActive").addClass("active")</script>

<div class="card">
    <div class="row">
        <div class="col-md-12 pt-1">
            <h2 class="text-center alert bg-yellow bg-darken-2 box-shadow-1" style="background-color:#ffffff;"> کهاتدار , مشتري , بانک یا صراف راجستر کولو فارم</h2>
        </div>
    </div>
    <div class="card-content">
        <div class="card-body">
            <ul class="nav nav-tabs nav-top-border no-hover-bg">
                <li class="nav-item">
                    <a class="nav-link active" id="baseIcon-tab11" data-toggle="tab" aria-controls="tabIcon11" href="#tabIcon11" aria-expanded="true"><i class="fa fa-user"></i> کهاتدار</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " id="baseIcon-tab12" data-toggle="tab" aria-controls="tabIcon12" href="#tabIcon12" aria-expanded="false"><i class="fa fa-user"></i>مشترې</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " id="baseIcon-tab13" data-toggle="tab" aria-controls="tabIcon13" href="#tabIcon13" aria-expanded="false"><i class="fa fa-home"></i>بانک / صراف</a>
                </li>
            </ul>
            <div class="tab-content pt-1">
                <div role="tabpanel" class="tab-pane active" id="tabIcon11" aria-expanded="true" aria-labelledby="baseIcon-tab11">
                    @await Html.PartialAsync("~/views/Dealer/_DealerPartial.cshtml")
                </div>
                <div class="tab-pane " id="tabIcon12" aria-labelledby="baseIcon-tab12">
                    @await Html.PartialAsync("~/views/Dealer/_CustomerPartial.cshtml")
                </div>
                <div class="tab-pane " id="tabIcon13" aria-labelledby="baseIcon-tab13">
                    @await Html.PartialAsync("~/views/Dealer/_BankPartial.cshtml")
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Dealer/_BankPartial.cshtml
@model BankViewModel


<div class="modal-content user-view">
    <div class="modal-header bg-primary white">
        <h4 class="modal-title" id="myModalLabel100">بانک / صراف راجستر کول </h4>
    </div>
    <div class="modal-body">
        <form asp-controller="Dealer" data-ajax="true" asp-action="BankRegistration" data-ajax-success="funSuccessBank(data)" method="post" id="frmBank">
            <div class="row col-md-12 align-items-end justify-content-center pt-2">

                <input hidden asp-for="BankId" value="0" />

                <div class="form-group">
                    <label class="">بانک / صراف نوم:</label>
                    <input asp-for="NameB" class="form-control" />
                    <span asp-validation-for="NameB" class="text-danger"></span>
                </div>
                &nbsp;&nbsp;
                <div class="form-group">
                    <label class="">موبایل:</label>
                    <input asp-for="PhoneB" class="form-control" />
                    <span asp-validation-for="PhoneB" class="text-danger"></span>
                </div>
                &nbsp;&nbsp;
                <div class="form-group">
                    <label class="">آدرس:</label>
                    <input asp-for="AddressB" class="form-control" />
                    <span asp-validation-for="AddressB" class="text-danger"></span>
                </div>

                <div class="form-group col-md-2 user-insert">
                    <button type="submit" id="btnSubmitBank" class="btn btn-primary btn-icon-md">ذخیره</button>
                    <button type="reset" id="btnResetBank" class="btn btn-warning btn-icon-md">پاکول</button>
                </div>
            </div>
        </form>
        <section id="">
            <table class="table table-responsive-md table-striped table-condensed table-bordered dataTables_scrollHead" id="tblbanks">
                <thead class="scrollable-container ps--scrolling-x">
                    <tr role="row">
                        <th style="max-width:1%;">#</th>
                        <th class="col-md-1">بانک / صراف نوم</th>
                        <th class="col-md-1">موبایل </th>
                        <th class="col-md-1">آدرس</th>
                        <th class="col-md-1">حالت </th>
                        <th style="max-width:1%;" class=" user-edit">  تغیرول</th>
                        <th style="max-width:1%;" class=" user-delete">حذف</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </section>

    </div>
</div>

<form data-ajax="true" asp-action="DeleteBank" data-ajax-method="post" asp-controller="Dealer" data-ajax-success="deletedBank(data)">
    <input hidden  id="bankId" name="bankId" />
    <button type="submit" class="d-none" id="btnDeleteBank"></button>
</form>

<form data-ajax="true" asp-action="LockBankAccount" data-ajax-method="post" asp-controller="Dealer">
    <input hidden id="BankToLockb" name="BankId" />
    <input hidden id="tfb" name="trueFalse" />
    <button type="submit" class="d-none" id="btnLockb"></button>
</form>

<script>
    $(document).ready(function () {
        LoadBanks();
    })

    function LoadBanks() {
        $.ajax({
            url: "/Dealer/FetchBanks/",
            contentType: "application/json",
            datatype: "JSON",
            success: function (result) {

                var trr = "";
                $.each(result, function (i, col) {
                    var clss = "";
                    var spns = "";
                    if (col.status == "Unlocked") {
                        clss = "btn-primary";
                        spns = "fa fa-unlock";

                    } else {

                        clss = "btn-danger";
                        spns = "fa fa-lock";
                    }

                    trr += '<tr  role="row">' +
                        '<td >' + (i + 1) + '</td>' +
                        '<td >' + col.name + '</td>' +
                        '<td>' + col.phone + '</td>' +
                        '<td >' + col.address + '</td>' +
                        '<td ><button onclick="fnToggleBtnLockb(' + i + ',\'' + col.bankId + '\')" id=b' + i + ' class="btn btn-float btn-round btn-float-md   ' + clss + '"><i id="spanb' + i + '" class="' + spns + '" ></i></button></td>' +
                        ' <td  class="user-edit"><button type="button" onclick="fnEditBank(' + col.bankId + ',\'' + col.name + '\',\'' + col.address + '\',\'' + col.phone + '\')" class="btn btn-primary"><i class="fa fa-edit"></i></button></td>' +
                        ' <td  class="user-delete"><button type="button" onclick="fnDeleteBank(' + col.bankId + ')" class="btn btn-danger"><i class="fa fa-trash"></i></button></td>' +
                        '</tr>';

                })
                var table = $("#tblbanks").dataTable();
                table.fnDestroy();
                $("#tblbanks>tbody").html("").html(trr);

                $("#tblbanks").DataTable({
                    stateSave: true,
                    "lengthMenu": [[5, 10, 20, -1], [5, 15, 50, "ټول"]],
                    "pageLength": 5,
                    "language": {
                        "emptyTable": "په جدول کې معلومات شتون نه لري",
                        "info": "د <b>( _START_  )</b> تر <b>( _END_  )</b> د <b>( _TOTAL_ )</b> ریکاروډونو څخه."
                        ,
                        "infoFiltered": "( <b>( _MAX_ )</b> ریکارډونه شتون لرې )",
                        "lengthMenu": "ښودل_MENU_ ریکارډونو",
                        "search": "پلټنه<span class='fa fa-search'></span> ",
                        "searchPlaceholder": "پلټنه",
                        "zeroRecords": "پدی نوم هیڅ ریکارډ پیدا نشو ",
                        "paginate": {
                            "first": "لومړۍ پاڼه",
                            "previous": "مخکې",
                            "next": "وروسته",
                            "last": "پای"
                        },
                    },

                });
            }
        })
    }

    function fnToggleBtnLockb(i, BankId) {
        if ($("#b" + i).hasClass("btn-danger")) {
            $("#tfb").val("unlock");
            $("#BankToLockb").val(BankId);
            $("#btnLockb").trigger("click");
            $("#b" + i).removeClass("btn-danger").addClass("btn-primary");
            $("#spanb" + i).removeClass("fa fa-lock").addClass("fa fa-unlock");

        } else {
            $("#tfb").val("lock");
            $("#BankToLockb").val(BankId);
            $("#btnLockb").trigger("click");
            $("#b" + i).removeClass("btn-primary").addClass("btn-danger");
            $("#spanb" + i).removeClass("fa fa-unlock").addClass("fa fa-lock");

        }
    }

    function funSuccessBank(data) {
        LoadBanks();
        $("#frmBank")[0].reset();
        toast(data, 'success');
        $("#btnSubmitBank").text("ذخیره");
    }

    function fnEditBank(id, name, address, phone) {

        $("#BankId").val(id);
        $("#NameB").val(name);
        $("#AddressB").val(address);
        $("#PhoneB").val(phone);

        $("#btnSubmitBank").text("تغیرول");
    }

    function fnDeleteBank(comId) {
        $("#bankId").val(comId);
        swal({
            title: "آیا غواړی چې نوموړی ریکارډ حذف شې؟",
            text: "",
            icon: "warning",
            buttons: {
                cancel: {
                    text: "نه",
                    value: null,
                    visible: true,
                    className: "",
                    closeModal: true,
                },
                confirm: {
                    text: "هو",
                    value: true,
                    visible: true,
                    className: "",
                    closeModal: true
                }
            }

        }).then((isConfirm) => {
            if (isConfirm) {
                $("#btnDeleteBank").trigger("click");
            }
        });

    }

    function deletedBank(data) {
        toast(data, 'success');
        LoadBanks();
    }

    $("#btnResetBank").click(function () {
        $("#btnSubmitBank").text("ذخیره");
    })
</script>

Views/Dealer/_CustomerPartial.cshtml
@model CustomerViewModel



<div class="modal-content user-view ">
    <div class="modal-header bg-primary white">
        <h4 class="modal-title" id="myModalLabel100">مشتریانو راجستر کول </h4>
    </div>
    <div class="modal-body">
        <form asp-controller="Dealer" data-ajax="true" asp-action="CustomerRegistration" data-ajax-success="funSuccessCustomer(data)" method="post" id="frmCustomer">
            <div class="row col-md-12 align-items-end justify-content-center pt-2 m-auto">
                <input hidden asp-for="CustomerId" value="0" />
                <div class="form-group">
                    <label  class="">مشترې نوم:</label>
                    <input asp-for="CusName" class="form-control" />
                    <span asp-validation-for="CusName" class="text-danger"></span>
                </div>
                &nbsp;&nbsp;
                <div class="form-group">
                    <label  class="">د پلار نوم:</label>
                    <input asp-for="CusFName" class="form-control" />
                    <span asp-validation-for="CusFName" class="text-danger"></span>
                </div>
                &nbsp;&nbsp;
                <div class="form-group">
                    <label  class="">آدرس:</label>
                    <input asp-for="CusAddress" class="form-control" />
                    <span asp-validation-for="CusAddress" class="text-danger"></span>
                </div>
                &nbsp;&nbsp;
                <div class="form-group">
                    <label class="">موبایل:</label>
                    <input asp-for="CusPhone" class="form-control" />
                    <span asp-validation-for="CusPhone" class="text-danger"></span>
                </div>

                <div class="form-group col-md-2  user-insert">
                    <button type="submit" id="btnSubmitCustomer" class="btn btn-primary btn-icon-md">ذخیره</button>
                    <button type="reset" id="btnResetCustomer" class="btn btn-warning btn-icon-md">پاکول</button>
                </div>
            </div>
        </form>
        <section id="divTable">
            <table class="table table-responsive-md table-striped table-condensed table-bordered dataTables_scrollHead" id="tblCustomer">
                <thead class="scrollable-container ps--scrolling-x">
                    <tr role="row">
                        <th style="max-width:1%;">#</th>
                        <th class="col-md-1">مشترې نوم</th>
                        <th class="col-md-1">پلار نوم</th>
                        <th class="col-md-1">آدرس</th>
                        <th class="col-md-1">موبایل </th>
                        <th class="col-md-1">حالت </th>
                        <th style="max-width:1%;" class="user-edit">  تغیرول</th>
                        <th style="max-width:1%;" class="user-delete">حذف</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </section>

    </div>
</div>

<form data-ajax="true" asp-action="DeleteCustomer" data-ajax-method="post" asp-controller="Dealer" data-ajax-success="deletedCustomer(data)">
    <input hidden id="customerIdd" asp-for="CustomerId" />
    <button type="submit" class="d-none" id="btnDeleteCustomer"></button>
</form>

<form data-ajax="true" asp-action="LockAccount" data-ajax-method="post" asp-controller="Dealer">
    <input hidden id="dealerToLock" name="dealerId"  />
    <input hidden id="tf" name="trueFalse"/>
    <button type="submit" class="d-none" id="btnLock"></button>
</form>

<script>
        $(document).ready(function () {

            LoadCustomers();
        })

        function LoadCustomers() {
            $.ajax({
                url: "/Dealer/FetchCustomers/",
                type: "POST",
                contentType: "application/json",
                datatype: "JSON",
                success: function (result) {
                    var tr = "";
                    $.each(result, function (i, col) {

                        if (col.status == "Unlocked") {
                            cls = "btn-primary";
                            spn = "fa fa-unlock";

                        } else {

                            cls = "btn-danger";
                            spn = "fa fa-lock";
                        }

                        tr += '<tr  role="row">' +
                            '<td >' + (i + 1) + '</td>' +
                            '<td >' + col.name + '</td>' +
                            '<td >' + col.fName + '</td>' +
                            '<td >' + col.address + '</td>' +
                            '<td>' + col.phone + '</td>' +
                            '<td ><button onclick="fnToggleBtnLock(' + i + ',\'' + col.customerId + '\')" id=' + i + ' class="btn btn-float btn-round btn-float-md   ' + cls + '"><i id="span' + i + '" class="' + spn + '" ></i></button></td>' +
                            ' <td  class="user-edit"><button type="button" onclick="fnEditCustomer(' + col.customerId + ',\'' + col.name + '\',\'' + col.fName + '\',\'' + col.address + '\',\'' + col.phone + '\')" class="btn btn-primary"><i class="fa fa-edit"></i></button></td>' +
                            ' <td  class="user-delete"><button type="button" onclick="fnDeleteCustomer(' + col.customerId + ')" class="btn btn-danger"><i class="fa fa-trash"></i></button></td>' +
                            '</tr>';

                    })
                    var table = $("#tblCustomer").dataTable();
                    table.fnDestroy();
                    $("#tblCustomer>tbody").html("").html(tr);

                    $("#tblCustomer").DataTable({
                            stateSave: true,
                            "lengthMenu": [[5, 10, 20, -1], [5, 15, 50, "ټول"]],
                            "pageLength": 5,
                            "language": {
                                "emptyTable": "په جدول کې معلومات شتون نه لري",
                                "info": "د <b>( _START_  )</b> تر <b>( _END_  )</b> د <b>( _TOTAL_ )</b> ریکاروډونو څخه."
                                ,
                                "infoFiltered": "( <b>( _MAX_ )</b> ریکارډونه شتون لرې )",
                                "lengthMenu": "ښودل_MENU_ ریکارډونو",
                                "search": "پلټنه<span class='fa fa-search'></span> ",
                                "searchPlaceholder": "پلټنه",
                                "zeroRecords": "پدی نوم هیڅ ریکارډ پیدا نشو ",
                                "paginate": {
                                    "first": "لومړۍ پاڼه",
                                    "previous": "مخکې",
                                    "next": "وروسته",
                                    "last": "پای"
                                },
                            },

                        });
                },
                error: function (err) {
                    console.log(err);
                }
            })
    }

    function fnToggleBtnLock(i, dealerId) {
        if ($("#" + i).hasClass("btn-danger")) {
            $("#tf").val("unlock");
            $("#dealerToLock").val(dealerId);
            $("#btnLock").trigger("click");
            $("#" + i).removeClass("btn-danger").addClass("btn-primary");
            $("#span" + i).removeClass("fa fa-lock").addClass("fa fa-unlock");

        } else {
            $("#tf").val("lock");
            $("#dealerToLock").val(dealerId);
            $("#btnLock").trigger("click");
            $("#" + i).removeClass("btn-primary").addClass("btn-danger");
            $("#span" + i).removeClass("fa fa-unlock").addClass("fa fa-lock");

        }


        //< a href = "#" onclick = "fnToggleBtnLock('+i+')" id = '+i+' class="btn btn-float btn-round btn-float-md btn-danger" > <i class="fa fa-unlock"></i></a >
    }

        function funSuccessCustomer(data) {
                LoadCustomers();
            $("#frmCustomer")[0].reset();
              toast(data, 'success');
            $("#btnSubmitCustomer").text("ذخیره");
          }

        function fnEditCustomer(id, name, fname, address, phone) {

            $("#CustomerId").val(id);
            $("#CusName").val(name);
            $("#CusFName").val(fname);
            $("#CusAddress").val(address);
            $("#CusPhone").val(phone);

            $("#btnSubmitCustomer").text("تغیرول");
        }

    function fnDeleteCustomer(comId) {
            $("#customerIdd").val(comId);
            swal({
                title: "آیا غواړی چې نوموړی ریکارډ حذف شې؟",
                text: "",
                icon: "warning",
                buttons: {
                    cancel: {
                        text: "نه",
                        value: null,
                        visible: true,
                        className: "",
                        closeModal: true,
                    },
                    confirm: {
                        text: "هو",
                        value: true,
                        visible: true,
                        className: "",
                        closeModal: true
                    }
                }

            }).then((isConfirm) => {
                if (isConfirm) {
                    $("#btnDeleteCustomer").trigger("click");
                }
            });

        }

    function deletedCustomer(data) {
             toast(data, 'success');

            LoadCustomers();
    }

    $("#btnResetCustomer").click(function () {
        $("#btnSubmitCustomer").text("ذخیره کول");
    })
</script>